name: Install Poetry Bin
author: Giovanni Barillari <gi0baro@d4net.org>
description: Installs and configures Poetry
branding:
  icon: package
  color: blue
inputs:
  virtualenvs-create:
    description: Whether Poetry should create a virtualenv or not
    required: false
    default: true
  virtualenvs-in-project:
    description: Whether Poetry should create virtualenvs in the project directory or not
    required: false
    default: false
  virtualenvs-path:
    description: The Poetry virtualenv path
    required: false
    default: "{cache-dir}/virtualenvs"
runs:
  using: composite
  steps:
    - name: Install and configure Poetry
      run: |
        _version_target="$(mktemp)"
        _archive="$(mktemp)"

        if [ "${{ runner.os }}" == "Windows" ]; then
          _target_arch=x86_64-pc-windows-msvc
        elif [ "${{ runner.os }}" == "macOS" ]; then
          _target_arch=x86_64-apple-darwin
        else
          _target_arch=x86_64-unknown-linux-gnu
        fi

        curl -sSL https://api.github.com/repos/gi0baro/poetry-bin/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' > $_version_target
        _version=$(cat $_version_target)

        if [ "${{ runner.os }}" == "Windows" ]; then
          path="C:/Users/runneradmin/AppData/Roaming/PoetryBin"
          _binpath=$path
          _poetry=$_binpath/poetry.exe
        else
          path="$HOME/.local/poetry-bin"
          _binpath="$path/bin"
          _poetry=poetry
        fi

        echo -e "\n\033[33mSetting Poetry installation path as $path\033[0m\n"
        echo -e "\033[33mInstalling Poetry $_version\033[0m\n"

        curl -sSL https://github.com/gi0baro/poetry-bin/releases/download/$_version/poetry-bin-$_version-$_target_arch.tar.gz > $_archive
        mkdir -p $path
        tar xzf $_archive --directory $path

        echo "$_binpath" >> $GITHUB_PATH
        export PATH="$_binpath:$PATH"

        $_poetry config virtualenvs.create ${{ inputs.virtualenvs-create }}
        $_poetry config virtualenvs.in-project ${{ inputs.virtualenvs-in-project }}
        $_poetry config virtualenvs.path ${{ inputs.virtualenvs-path }}

        echo -e "\n\033[33mInstallation completed ✅\033[0m"

      shell: bash

    # - name: Windows PowerShell path
    #   run: |
    #     echo "C:/Users/runneradmin/AppData/Roaming/PoetryBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    #   if: ${{ runner.os == "Windows" }}
