on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: poetry --version

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: poetry --version

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: poetry --version
